[changelog]
header = """# Changelog

All notable changes to this project will be documented in this file.\n
"""
body = """
{%- macro remote_url() -%}
  https://github.com/Higangssh/homebutler
{%- endmacro -%}

{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}]({{ self::remote_url() }}/compare/{{ previous.version }}...{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]({{ self::remote_url() }}/compare/{{ previous.version }}...HEAD)
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}
{%- endfor %}
{% endfor %}
"""
footer = ""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "ğŸš€ Features" },
  { message = "^fix", group = "ğŸ› Bug Fixes" },
  { message = "^security", group = "ğŸ”’ Security" },
  { message = "^refactor", group = "â™»ï¸ Refactor" },
  { message = "^perf", group = "âš¡ Performance" },
  { message = "^docs", skip = true },
  { message = "^chore", skip = true },
  { message = "^test", skip = true },
  { message = "^style", skip = true },
  { message = "^ci", skip = true },
]
tag_pattern = "v[0-9].*"
sort_commits = "newest"
